### ISSUE TITLE
Update article + project

### ISSUE THREAD

**Issue by Nordes** [AndreyAkinshin/StephenToubBenchmarks#1]
Hi, 

Thank you for your tool. I think it would be nice to update your article (or write a new one) with this tool updated using the latest 3 frameworks (4.7.*, Mono 5.12.0.226 x64 and Core 2.1)

**Comment by AndreyAkinshin** [comment]
@Nordes, the original idea of the article was to show how BenchmarkDotNet can be useful for measurements which are described in https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/ Since the original post doesn't have any updates, I don't think that it makes sense to update mine.

If you are curious about the performance of .NET Framework 4.7.* / Mono 5.12.0.226 x64 / .NET Core 2.1, feel free to use the benchmarks from the blog posts for own performance experiments / blog posts / GitHub repositories.
